-- Masters 2018


Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('3','2002','2','3','4','7',null);
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('2','2003','2','2','2,5','2,5',null);
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('1','2002','3','1',null,null,null);
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('1','2001','3','1',null,null,null);
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('1','2003','3','1','6,2','12,4','50');
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('1','2004','3','1','4','7','50');
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('1','2005','3','1','4','7','50');
Insert into ORGANISATEURS (COMPETITION,ANNEE,NBREJOURS,SECRETARIAT,DROITINSCRIPTIONINDIVIDUEL,DROITINSCRIPTIONRELAIS,FORFAITPARCOURSE) values ('4','2015','2',null,null,null,null);
COMMIT;