-- Masters 2018


Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('A ','25/29 ans','25','29');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('B ','30/34 ans','30','34');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('C ','35/39 ans','35','39');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('D ','40/44 ans','40','44');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('E ','45/49 ans','45','49');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('F ','50/54 ans','50','54');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('G ','55/59 ans','55','59');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('H ','60/64 ans','60','64');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('I ','65/69 ans','65','69');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('J ','70/74 ans','70','74');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('K ','75/79 ans','75','79');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('L ','80/84 ans','80','84');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('M ','85/89 ans','85','89');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('N ','90/94 ans','90','94');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('O ','Plus de 94','94',null);
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('0 ','20/24','20','24');
Insert into CATEGORIES (CATEGORIE,LIBCATEGORIE,AGEMIN,AGEMAX) values ('9 ','moins de 20 ans',null,'19');
COMMIT;
