-- Masters 2018


Insert into COMPETITIONS (COMPETITION,LIBELLE,ORGANISATEUR) values ('1','Championnats de Belgique de Natation','FEDERATION ROYALE BELGE DE NATATION');
Insert into COMPETITIONS (COMPETITION,LIBELLE,ORGANISATEUR) values ('2','Challenge Jean-Baptiste Evrard','EMBOURG NATATION');
Insert into COMPETITIONS (COMPETITION,LIBELLE,ORGANISATEUR) values ('3','Challenge Alex EVERAERT','CHARLEROI ASSOCIATION NATATIOn');
Insert into COMPETITIONS (COMPETITION,LIBELLE,ORGANISATEUR) values ('4','Championnat Europe','FEDERATION Europe');
COMMIT;