-- Masters 2018


Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('USG  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('TENBO',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('OLD D',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('SL   ','Swimming Luxembourg',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNSW ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNMA ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZZV  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZVH  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('VU/DG',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('OCEAN',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('W    ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('IKZ  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('AZSC ','Koninklijke Antwerpsezwemclub Scaldis',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('AZV  ','Arendonkse zwemclub',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('BZTC ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CCM  ','Castor club de Mons',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CCS  ','Club communal natation Marche en Famenne',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CHAN ','Charleroi association natation',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CHTHN',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNA  ','Cercle de natation Arlonais',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNBA ','Cercle Royal de natation de Bruxelles Atalante',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNHUY','Cercle Royal de natation de Huy',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('CNJ  ','Cercle de natation Jodoignois',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('COUNT','Country swimming club la Calaine Neu-Moresnet',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('DCTP ','Dauphin club Trois Ponts',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('DMB  ','Zwemvereniging de Meerkoet Bree',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('EMBOU','Embourg natation',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ENN  ','Ecole de natation de Nivelles',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ESN  ','Ecole Seraing Natation',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('GBZ  ','Groot Beverse Zwemclub',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('HZA  ','Heistse zwemclub Arduas',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('HZC  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('HZS  ','Koninklijke Hasselte zwemvereniging Spartacus',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('KZK  ','Koninklijke Kortrijkse zwemkring',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('LDV  ','Les dauphins Visetois',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('LZV  ','Loverse zwemvereniging',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('MOZKA','Molse zwemclub Mozka',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('MZVA ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('NCG  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('NEREU','Cercle de natation Nereu Ganshoren',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('NOC  ','Namur Olympic club',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('NSG  ','Societe Royale La nage Saint-Gilles',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('OLMA ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('OSC  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('OZEKA',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('RBP  ','Koninkijke Antwerpsezwemclub scaldis',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('RSCM ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('SCC  ','Swimming club Calypso Watermael Boitsfort',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('SNC  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('SOZ  ','Sorghvliet zwemclub',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('SVAZ ','Sportvereniging Aarselaar zwemmen',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('TZV  ','Koninklijke Turnhoutse Zwemvereniging',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('VN   ','Royal Verviers natation',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('WSD  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('WZV  ','Wemmelse zwemvereniging',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('YSC  ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZCK  ','Zwemclub Kapelle-O/D-Bos',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZCM  ','Zwemclub Maasmechelen',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZD   ','Zolderse Dolfijnen',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZDKK ',null,null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZIK  ','Zwemclub iloka Kapellen',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZN   ','Nijlense Zwemclub',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZNA  ','Koninklijke zwemclub Neptunus Aalst',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZOLA ','Zwemclub Olympic Antwerpen',null);
Insert into CLUBS (CLUB,NOM,SECRETARIAT) values ('ZVL  ',null,null);
COMMIT;